### ISSUE TITLE
tiling does not start

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#12]
I've uploaded a few models, but they stay stuck at "pending"
The tiling server never starts or the files never get moved from wordpress site to s3.

![image](https://user-images.githubusercontent.com/13057505/75633058-d2ba3d00-5bcf-11ea-9f32-585eafe482b3.png)

Try uploading a small file to see if it works for you.

**Comment by 3DGISKing** [comment]
I see. I will try.

**Comment by 3DGISKing** [comment]
If service is restarted because of any error(maybe out of memory?), all preparation of construkted assets in progress will be suspended. 
This kind of situation will frequently happen when multiple asset preparation is in progress.
Actually at 02-27 many asset preparations were performed. 

How to solve this problem?
- let ‘s make sure construkted_api not run as service.
   so we can catch the moment exactly when the server is broken.
- let ‘s estimate how much memory is needed for asset preparation.
   let ‘s estimate how much asset preparation can be done at the same time.
- At now construkted_api is designed to do multiple asset preparation at the same time.
  But NodeODM is designed to do only one task at any time.
  Task is scheduled by queue.
  So what is a better idea?

- If service is restarted, it should restart the previous failed task.

**Comment by outsider787** [comment]
There are two main issues:
- Computer resources running out (CPU/RAM)
- Dealing with service restart/interrupted tasks

**Computer Resources**
Downlading a 5.0 GB point cloud takes around 30min and use 50-60% CPU and 200-300MB of RAM.
![image](https://user-images.githubusercontent.com/13057505/75670546-f078b800-5c4a-11ea-8fea-53791515d240.png)

I agree that we should create a queue system, but we should be careful how we design it. 
Only items that use too many compute resources should be queued. Some operations can take a long time, but are not cpu dependent. 
For example we should not wait for items to process on CesiumION. 

Maybe we only need to queue the following operations:
- downloading from CesiumION operation and
- tileToSQLite opertion

But let me do some research. I have an idea I want to check.

**Service restart/interrupted tasks**
I agree that if a task is interrupted, the service should re-try that task from the last successful step

**Comment by outsider787** [comment]
I need to think about solutions to those problems.

**Comment by outsider787** [comment]
Some tests I just did:

With 20 threads, 50-60% cpu usage 4 min download time.
![image](https://user-images.githubusercontent.com/13057505/75681831-5de41300-5c62-11ea-8aa4-8019d294ca4c.png)

With 5 threads, around 20% cpu usage: 8-9 min download time
 ![image](https://user-images.githubusercontent.com/13057505/75681640-faf27c00-5c61-11ea-8c5d-757152d52da2.png)

With 3 threads, around 10% cpu usage, 16-18min download time
![image](https://user-images.githubusercontent.com/13057505/75681696-1fe6ef00-5c62-11ea-8ee5-25fd8f9c9a7d.png)

**Comment by outsider787** [comment]
**Computer Resources**
I think for right now we reduce the number of threads used in the asset-downloader script to 3 threads. This should allow 5-6 instances of the script to be running and still have cpu power for other tasks.

We can design a queue system at a later time.

**Service restart/interrupted tasks**
This issue still needs to be addressed. 
#13
