### ISSUE TITLE
fix memory bug on Zhefeng asset server

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#22]
There is a memory bug which fills up the server ram.

Low priority job.

![image](https://user-images.githubusercontent.com/13057505/76701836-2d0cd080-669b-11ea-9d20-dbe8b73f3871.png)

**Comment by 3DGISKing** [comment]
PHP FastCGI Process Manager (PHP-FPM) is an alternative FastCGI daemon for PHP that allows a website to handle high loads. PHP-FPM maintains pools (workers that can respond to PHP requests) to accomplish this. 

https://documentation.cpanel.net/display/78Docs/PHP-FPM

So I guess the reason.
1 It is because we allow too many pools.
https://stackoverflow.com/questions/15364735/php-fpm-taking-too-much-memory
https://stackoverflow.com/questions/27614511/why-php-fpm-nginx-takes-much-ram-memory

2 because there are some bugs related to memory in my php script(3D tile server).

**Comment by outsider787** [comment]
Ok.
I will leave this issue open.
IF we go back to using "Zhefeng asset-server" we will re-visit this issue.

**Comment by 3DGISKing** [comment]
Ok.

**Comment by outsider787** [comment]
Did you find any bugs or fix any issues on  "Zhefeng asset-server"?

**Comment by 3DGISKing** [comment]
Not yet.

**Comment by outsider787** [comment]
for now the asset server gets rebooted every night.
Temporary fix.
