### ISSUE TITLE
Delete item fails

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#4]
When deleting an item from the MY ASSETS page ( https://gw3.construkted.com/profile/?active_tab=posts ) I get an error, and the post does not get deleted.

![image](https://user-images.githubusercontent.com/13057505/75204160-221aec00-573e-11ea-96a2-92e4516f17a7.png)

**Comment by 3DGISKing** [comment]
I have just tested one sample, it is ok. please le me know asset slug.

**Comment by outsider787** [comment]
I will do more testing. 
Leaving issue open until my testing is complete.

**Comment by outsider787** [comment]
I have another asset which has this problem.
If you log into my ADMIN account, you'll see an asset with the title CAN'T DELETE
https://gw3.construkted.com/profile/?active_tab=posts

**Comment by 3DGISKing** [comment]
Why failed?
Because construkted_api sends errors.  why?
When the user clicks the delete button, WP requests the deleting asset to construkted_api.
At that time WP sends the request with userName, slug and original3DFileBaseName parameter. 
construkted_api check if original uploaded zip file and generated sqlite file exists on server  with these parameters.
If either original uploaded zip file or corresponding 3d file does not exist on server, construkted sends error.

This is construkted_api code snippet for deleting asset.

https://github.com/outsider787/construkted_api/blob/c694da2835e164ef249a50cdece4a5698218fc03/app.js#L145-L190

**Comment by 3DGISKing** [comment]
https://github.com/outsider787/gw3_construkted/blob/7e628eb5cc064fd57e9425b58f3b709d9aee52aa/wp-content/themes/gowatch-child/includes/ajax.php#L131-L164

**Comment by outsider787** [comment]
Another delete error.
I clicked delete for asset number r3ld8ssuf3.
I waited for a few seconds, and then a new error came up:
![image](https://user-images.githubusercontent.com/13057505/75618047-40b22600-5b36-11ea-84d4-663a3e18e8ad.png)

**Comment by 3DGISKing** [comment]
I believe this error comes from 

https://github.com/outsider787/gw3_construkted/blob/e110fded78e9183beb7a1b23f6e39ea9dd00b47c/wp-content/themes/gowatch-child/includes/ajax.php#L148

This code tries to send requests to construkted_api but sometimes it may fail because of network problems.
I think this is a network issue in your end.

**Comment by outsider787** [comment]
Yes, it's a network issue, but it's not something I can fix. Sometimes the network will take some time to respond.

If an error is returned, because some network issue, the error message should read:
"Error due to network issues. Please try again in a few moments"

Each time the delete button is pressed the code should try and delete the 3d tile, zip file and remove the post from WP, until everything is removed. 

From the user perspective, they just want the item deleted. If they click delete and it doesn't work, they will click it again.

**Comment by 3DGISKing** [comment]
I agree with that the error message "Error due to network issues. Please try again in a few moments" should be shown when a network problem happens.

**Comment by outsider787** [comment]
I cannot delete some items.
The error message says "There was en error deleting asset"

![image](https://user-images.githubusercontent.com/13057505/76700584-56bffa80-668f-11ea-9e30-c9ed305d323d.png)

**Comment by 3DGISKing** [comment]
I believe this is because of the construkted_api goes down.
![image](https://user-images.githubusercontent.com/26606704/76703271-814f9900-670b-11ea-9ad8-b3891352d047.png)

**Comment by 3DGISKing** [comment]
I have tried. It works. asset test and 3101 was deleted. please try deleting asset test 3100

**Comment by outsider787** [comment]
yes, I also tried on another asset and it worked.
Closing issue.
